### PR TITLE
Trino rebranding and deprecation notice 

### PR DESCRIPTION
**Pull request by leniartek**
*Trino rebranding
*Deprecation notice

### CODE REVIEW

**Comment by findepi** [comment]
cc @trinodb/maintainers

**Comment by findepi** [comment]
@leniartek did you file the CLA?

**Comment by leniartek** [comment]
@findepi yes, about 5 minutes before pull request :)

**Comment by findepi** [comment]
@leniartek please check the build

@martint can you please help with the CLA?

**Comment by leniartek** [comment]
retest this please

**Comment by leniartek** [comment]
@findepi CLA passed.
Looks like CI is failing because of dependencies. 
```
Err https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages
  Could not resolve host: apt.dockerproject.org
Err https://apt.dockerproject.org ubuntu-trusty/main i386 Packages
  Could not resolve host: apt.dockerproject.org
```
I don't think we should invest time in fixing this as this repo will be deprecated.

**Comment by losipiuk** [comment]
LGTM. Please squash the commits.

**Comment by leniartek** [comment]
@losipiuk squash done.

**Review by losipiuk — APPROVED** [review]

**Pull request merged**
